### ISSUE TITLE
Near and Far End ES/SES and UAS PM data

### ISSUE THREAD

**Issue by ciena-1** [OpenROADM/OpenROADM_MSA_Public#23]
The PM types defined in org-openroadm-pm-types.yang seem to be missing Errored Second / Severely Errored Second, and Unavailable Second PM counts for near and far end.   There appears to be some duplication of ES/SES values called out against Ethernet PM, but OTN layer PM values seem to be missing.

**Comment by fgruman** [comment]
Fixed in 3.1.  
The ES, SES, UAS are now generic.

NEND vs FEND would specified by the location attribute.

**Comment by dhruv2180** [comment]
@ciena-1 closing the issue, let us know if you have any questions.
