### ISSUE TITLE
node-id-type length is miss-matching with Pattern regular expression

### ISSUE THREAD

**Issue by ashuagarwal01** [OpenROADM/OpenROADM_MSA_Public#28]
Hi,

The node-id-type length is defined as 7..63.  But the pattern is limiting the length to 20 characters. 

typedef node-id-type {
    type string {
      length "**7..63**";
      pattern "([a-zA-Z][a-zA-Z0-9-]**{5,18}**[a-zA-Z0-9])" {
        error-message
          "A node-id must be 7 to 63 characters in length.
           A node-id can contain letters, numbers, and hyphens.
           The first character must be a letter.
           The last character must be a letter or number.";
      }

The correct pattern should be like this:
pattern "([a-zA-Z][a-zA-Z0-9-]**{5,61}**[a-zA-Z0-9])"

**Comment by fgruman** [comment]
Fixed in 5.0:
  typedef node-id-type {
    type string {
      length "7..63";
      pattern "([a-zA-Z][a-zA-Z0-9-]{5,61}[a-zA-Z0-9])" {

**Comment by dhruv2180** [comment]
@ashuagarwal01 this issue has been addressed, closing the issue, let us know if you still have any questions.
