### ISSUE TITLE
Space in directory structure is painful

### ISSUE THREAD

**Issue by bclaise** [OpenROADM/OpenROADM_MSA_Public#5]
Hi,

Would it be possible to remove the spaces, to ease automation?
 	Version 1.0 	
	Version 1.1.1 	
	Version 1.1 	
	Version 1.2.1 	
	Version 1.2

**Comment by fgruman** [comment]
I think this has been addressed in latest versions (now using branches for versions, not directories)

**Comment by dhruv2180** [comment]
Closing the issue, let us know if you have any questions.
